from models.base import base
from models.bagging import baggingRegression
from models.linearRegression import linear,ridge,lasso,elasticNet
from models.SVR import SVMRegression
from models.treeRegression import dtRegression,rfRegression,gbRegression
from models.xgb import xgbRegression,xgbRegression_dart
from models.lgbm import lgbmRegression,lgbmRegression_dart,lgbmRegression_goss
from models.catboost import catBoostRegression
from models.ANNRegression import ANNRegression
from models.TabNet import TabNetRegression